AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  braze-update-workflow

  Sample SAM Template for Python step functions workflow

Parameters:
  Env:
    #Type: AWS::SSM::Parameter::Value<String>
    Type: String
    Default: local 
    Description: >
      Environment in which the application will be deployed.
      Allowed values [local, qa, live]]

Mappings:
  VpcConfigMapping:
    local:
      SecurityGroupIds: []
      SubnetIds: []
    qa:
      SecurityGroupIds:
        - sg-03f283e3f37b18d4e
        - sg-0c5ee036f6327d50d
      SubnetIds:
        - subnet-0fd461b1b954b7d2c
        - subnet-caa4ba83
    live:
      SecurityGroupIds: []
      SubnetIds: []

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: braze-update-workflow 
      DefinitionUri: src/statemachine/braze_update_workflow.asl.json
      DefinitionSubstitutions:
        BrazeSenderArn: !GetAtt BrazeSender.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref BrazeSender
        - DynamoDBCrudPolicy:
            TableName: !Ref BrazeRateLimitsTable

  BrazeSender:
      Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
      Properties:
        CodeUri: src/functions/braze_sender
        Handler: app.lambda_handler
        Runtime: python3.9
        Architectures:
          - x86_64
        Timeout: 120
        VpcConfig:
          SecurityGroupIds: !FindInMap [ VpcConfigMapping, !Ref Env, SecurityGroupIds ]
          SubnetIds: !FindInMap [ VpcConfigMapping, !Ref Env, SubnetIds ]
        Environment:
          Variables:
            ENVIRONMENT: !Ref Env #'{{resolve:ssm:environment}}'
            # VAULT_URL: '{{resolve:secretsmanager:vault:SecretString:url}}'
            # VAULT_TOKEN: '{{resolve:secretsmanager:vault:SecretString:token}}'
            # VAULT_MOUNT_POINT: '{{resolve:secretsmanager:vault:SecretString:mount-point}}'

  BrazeRateLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BrazeRateLimits
      AttributeDefinitions:
        - AttributeName: RequestType
          AttributeType: S
      KeySchema:
        - AttributeName: RequestType
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: RateLimitReset
        Enabled: true

  CanvasTriggerSendQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CanvasTriggerSendQueue

  TrackUsersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TrackUsersQueue

  NewUserAliasQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CanvasTriggerSendQueue

  EventBridgePipesRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - pipes.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ReadCanvasTriggerSendQueue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !GetAtt CanvasTriggerSendQueue.Arn
        - PolicyName: ReadTrackUsersQueue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !GetAtt TrackUsersQueue.Arn
        - PolicyName: ReadNewUserAliasQueue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !GetAtt NewUserAliasQueue.Arn
        - PolicyName: ExecuteStepFunction
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource: !Ref StateMachine

  CanvasTriggerSendPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: CanvasTriggerSendPipe
      RoleArn: !GetAtt EventBridgePipesRole.Arn
      Source: !GetAtt CanvasTriggerSendQueue.Arn
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      Target: !Ref StateMachine
      TargetParameters:
        StepFunctionStateMachineParameters:
          InvocationType: FIRE_AND_FORGET

  TrackUsersPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: TrackUsersPipe
      RoleArn: !GetAtt EventBridgePipesRole.Arn
      Source: !GetAtt TrackUsersQueue.Arn
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      Target: !Ref StateMachine
      TargetParameters:
        StepFunctionStateMachineParameters:
          InvocationType: FIRE_AND_FORGET

  NewUserAliasPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: NewUserAliasPipe
      RoleArn: !GetAtt EventBridgePipesRole.Arn
      Source: !GetAtt NewUserAliasQueue.Arn
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      Target: !Ref StateMachine
      TargetParameters:
        StepFunctionStateMachineParameters:
          InvocationType: FIRE_AND_FORGET