AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  campaign-segmentation-workflow

  Sample SAM Template for Python step functions workflow.

Parameters:
  Env:
#    Type: AWS::SSM::Parameter::Value<String>
    Type: String
    Default: local 
    Description: >
       Environment in which the application will be deployed.
       Allowed values [local, qa, live]]

Mappings:
  VpcConfigMapping:
    local:
      SecurityGroupIds: []
      SubnetIds: []
    qa:
      SecurityGroupIds:
        - sg-03f283e3f37b18d4e
        - sg-0c5ee036f6327d50d
      SubnetIds:
        - subnet-0fd461b1b954b7d2c
        - subnet-caa4ba83
    live:
      SecurityGroupIds: []
      SubnetIds: []

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    VpcConfig:
      SecurityGroupIds: !FindInMap [ VpcConfigMapping, !Ref Env, SecurityGroupIds ]
      SubnetIds: !FindInMap [ VpcConfigMapping, !Ref Env, SubnetIds ]
    Environment:
      Variables:
        ENVIRONMENT: !Ref Env #'{{resolve:ssm:environment}}'
#        VAULT_URL: '{{resolve:secretsmanager:vault:SecretString:url}}'
#        VAULT_TOKEN: '{{resolve:secretsmanager:vault:SecretString:token}}'
#        VAULT_MOUNT_POINT: '{{resolve:secretsmanager:vault:SecretString:mount-point}}'

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: campaign-segmentation-workflow
      DefinitionUri: src/statemachine/abandoned_cart_workflow.asl.json
      DefinitionSubstitutions:
        PrepareBrazeMessagesArn: !GetAtt PrepareBrazeMessages.Arn
        SelectAudienceArn: !GetAtt SelectAudience.Arn
      Events:
        ScheduleDafitiBR:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Dafiti Brasil
            Enabled: True
            Schedule: "rate(10 minutes)"
            Input:
              '{
                "campaign": "abandoned_cart_general",
                "country": "BR",
                "store": "DAFITI",
                "visit_time_range": {
                  "start": 30,
                  "end": 20,
                },
                "braze": {
                  "canvas_id": "XPTO",
                  "objects_limit": 50
                }
              }'
        ScheduleDafitiAR:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Dafiti Argentina
            Enabled: False
            Schedule: "rate(10 minutes)"
            Input:
              '{
                "campaign": "abandoned_cart_general",
                "country": "AR",
                "store": "DAFITI",
                "visit_time_range": {
                  "start": 30,
                  "end": 20,
                },
                "braze": {
                  "canvas_id": "XPTO",
                  "objects_limit": 50
                }
              }'
        ScheduleDafitiCH:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Dafiti Chile
            Enabled: False
            Schedule: "rate(10 minutes)"
            Input:
              '{
                "campaign": "abandoned_cart_general",
                "country": "CH",
                "store": "DAFITI",
                "visit_time_range": {
                  "start": 30,
                  "end": 20,
                },
                "braze": {
                  "canvas_id": "XPTO",
                  "objects_limit": 50
                }
              }'
        ScheduleDafitiCO:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Dafiti Colombia
            Enabled: False
            Schedule: "rate(10 minutes)"
            Input:
              '{
                  "campaign": "abandoned_cart_general",
                  "country": "CO",
                  "store": "DAFITI",
                  "visit_time_range": {
                    "start": 30,
                    "end": 20,
                  },
                  "braze": {
                    "canvas_id": "XPTO",
                    "objects_limit": 50
                  }
                }'
        ScheduleTricae:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Tricae
            Enabled: False
            Schedule: "rate(10 minutes)"
            Input:
              '{
                "campaign": "abandoned_cart_general",
                "store": "TRICAE",
                "visit_time_range": {
                  "start": 30,
                  "end": 20,
                },
                "braze": {
                  "canvas_id": "XPTO",
                  "objects_limit": 50
                }
              }'
        ScheduleKanui:
          Type: Schedule
          Properties:
            Description: Schedule to run the machine every 10 minutes to Kanui
            Enabled: False
            Schedule: "rate(10 minutes)"
            Input:
              '{
                "campaign": "abandoned_cart_general",
                "store": "KANUI",
                "visit_time_range": {
                  "start": 30,
                  "end": 20,
                },
                "braze": {
                  "canvas_id": "XPTO",
                  "objects_limit": 50
                }
              }'
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PrepareBrazeMessages
        - LambdaInvokePolicy:
            FunctionName: !Ref SelectAudience

  PrepareBrazeMessages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/prepare_braze_messages/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  SelectAudience:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/select-audience/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64